---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

require:
  - rubocop-packaging

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - gemfiles/**/*
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.0

RSpec/ExampleLength:
  # default 5
  Max: 12

RSpec/MultipleExpectations:
  # default 1
  Max: 4
