ARG RUBY_VERSION=3
FROM ruby:${RUBY_VERSION}-alpine

ARG UID

ENV DEVEL=1
ENV LANG=C.UTF-8
ENV RAILS_ENV=development

RUN apk update && apk add --no-cache build-base chromium tzdata

RUN gem install bundler
RUN echo 'gem: --no-document' > /etc/gemrc

RUN adduser -u ${UID} -D app 
RUN mkdir -p /home/app && chown -R app:app /home/app
RUN chown -R app /usr/local/bundle 

COPY . /app
