---
name: Specs Rails 7.1

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.2', '3.4']

    env:
      RAILS_VERSION: 7.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Database setup
        run: bin/rails db:create db:migrate db:test:prepare

      - name: Run tests
        run: bundle exec rspec --profile

      - name: On failure, archive screenshots as artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-failed-screenshots
          path: spec/dummy/tmp/screenshots
